name: Project Work 5 Run Tests on Main 

on:
    push:
        branches:
            - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      with:
        path: main

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: Run tests.sh
      run: bash ./project/tests.sh
